/*//==============================================================================//
//======================== HTTP Review =========================//
video page:
- incosistent use of backticks to wrap GET/POST
- 'to send the host name in a Host request header to the server.'
- backticks: ' Host header'
- 'to this rule, and they'
- use 'the/a' in answers to 1 and 2.
- ' although'

___

___

issues with the whole book are in the first section, followed by sections that separate the issues of individual chapters.

___

- backticks (ex: 'with "http://").', Query String Components table, ASCII code table)
- inconsistent capitalization of:
  - 'internet'
  - 'javascript'
- inconsistent wrapping of urls in quotes, backticks, anchors, or code blocks
- 'a lot'
- incosistent use of backticks to wrap terms like GET, POST, XSS, header names, etc
- 'request/response'
- inconsistent use of hyphen in 'client side' and 'server side'

___

- 'a long time - years, perhaps decades - and'
- ' letters H, T, T, P, followed by the colon, slash, slash, w, w, w then '
- 'If you're like most people, you've been using the internet for a long time - years, perhaps decades - and typing in those pesky URL addresses at the top of your browser, starting with the letters H, T, T, P, followed by the colon, slash, slash, w, w, w then the domain, over and over and over, yet never knowing or caring to know about what it stood for.'
- ' basic concepts around HTTP'
- ' people interested in understanding '
- ' lays the foundational knowledge to learning '
- 'reading oriented. That is, there are not a lot of exercises, because this is mostly a book about concepts.'

___

- ' you expect to see the website displayed in your browser. '
- 'and submit again'
- 'the interface or window, through '
- ' Javascript, '
- '--' (x2+...)
- ' displaying the page'
- 'browser address bar'
- 'system of rules, a protocol, that serve as a'
- ' request response protocol.'
- ' changes from its inception'
- ' form returning only '
- 'document version HTTP/0.9 was '
- ' file types like CSS documents'
- ' Address or IP Address and is '
- ' communication purpose to that device '
- 'we do not type'
- ' Domain Naming System or DNS.'
- ' names like http://www.google.com to an '
- 'address and maps '
- 'to an IP address 197.251.230.45. '
- ' address like http://www.google.com, instead '
- ' a number of digits.'
- ' starts with a web browser when you:'
- ' your devices' network '
- ' the Internet where '
- 'a remote computer or a server. '
- 'network interface which hands'
- ' its components and send '
- ' browser will then process '
- 'Google and Twitter'
- 'Twitter means'
- 'browser was issuing'
- ' basis called a Web'
- ' Safari and Chrome'
- 'Chrome, including mobile versions. '
- 'requests and processing the HTTP response'
- 'processing the HTTP response in a user-friendly manner onto your screen. '
- ' around, as there are '
- singular/plural: 'requests, and their job is to issue a response '
- ' the response they send back contains relevant data as specified in the request.'
- 'gotealeaf.com': 'https://d186loudes4jlv.cloudfront.net/http/images/http_client_server.png'
- 'Resource is a generic term '
- 'for things '
- 'This includes '
- 'web pages and other'
- 'trade stock'...?
- 'request/response' (x2+...)
- 'to be aware of HTTP as a '
- 'protocol and'
- 'and the impact it has'
- 'Both these reasons make HTTP a'
- 'stateless that means'
- 'internal Facebook page'
- 'click on the picture'
- 'but you do not expect'
- ' logged out after that action'
- ' data from you vs. any other user'
- 'It's both what makes'
- 'so resilient and distributed and hard to control'
- 'as well what'
- 'Internet works along'
- 'This chapter covered ... You also learned ... We'll'
- 'what an address such as http://www.google.com is and what it's'

___

- 'house address'
- ' tell one from the other'
- ' looks like vs. a phone'
- 'There's a similar concept for finding'
- 'games page'
- ' address resulting'
- 'the resource being returned'
- ' http://www.facebook.com/games ... https://www.facebook.com/games'
- 'Uniform Resource Locator or URL.'
- ' like that address'
- 'Uniform Resource Identifier or URI,'
- 'A URL is the most frequently used part of the general concept of a Uniform Resource Identifier or URI, which specifies how resources are located.'
- 'its components and what'
- 'When you see a URL, such as "http://www.example.com:88/home?item=book", it's comprised of several components.'
- '5 parts'
- 'before the colon and two forward slashes and'
- ' In this case it'
- 'Hypertext Transfer Protocol or HTTP'
- 'make a request'
- 'mailto or git'
- 'hosted or located.'
- 'port or port number'
- 'a port other than the default.'
- '/home? ... /home/ (in list item and image)'
- 'shows what local resource is being requested'
- '`://`'
- 'example.com server.'
- 'port number which the host uses'
- 'to listen to HTTP requests'
- 'form of: http://localhost:3000/profile is'
- ' is port 80'
- 'one has to'
- 'Query Strings/Parameters'
- periods after Descriptions in query string table
- 'name/value pairs' (x2+...)
- 'size=32gb and color=white'
- 'color=white are'
- ' narrow down on a product'
- ' size 32gb and color'
- ' server side'
- 'Another common place where you may have seen query parameters in action is when you perform a search'
- 'type in a URL into'
- ' you're issuing HTTP GET requests'
- last image doesn't have transparent background, like all the previous ones -- jpg instead of png: 'https://d186loudes4jlv.cloudfront.net/http/images/query_strings.jpg'
- ' great to pass in additional information to the server'
- 'server, however, there are some limits to the use of'
- 'a lot of data to pass on'
- 'you will not be able'
- 'information like username or password to'
- 'server in this manner'
- 'Space and special characters like & cannot'
- 'used with query strings'
- 'As such, unsafe or reserved characters not included in this set have to be converted or encoded to conform to this format.'
- 'URL encoding serves the purpose'
- 'characters with a % symbol ... the character'
- 'symbol followed by'
- 'characters and example URLs:'
- singular/plural: 'Characters  must be encoded if:' ... list items
- 'For example % is'
- 'reserved for a special meaning'
- ' their presence in a URL serve'
- 'Characters such as /, ? :, @ and & are'
- encoded numbers 2 and 3 seem equivalent...
- 'For example & is'
- ': is also reserved to'
- 'delimit host/port components and user/password.'
- ' alphanumeric and special characters $-_.+!'()", and reserved characters when'
- 'special characters $-_.+!'()"'
- 'As long as a character is not being used for its reserved purpose'
- 'we've discussed ... We also looked'
- 'of the URL and concluded by exploring'
- ' into requests and responses and what they comprise of after the'
- 'preparations chapter.'

___

- 'the tools we'll use in this book to demonstrate'
- 'a few tools you'll need to follow along'
- 'Note that you only need one of the tools listed.'
- 'It is important to note that you will be able to follow this book'
- 'Graphical HTTP tools'
- ' there is a limited Trial version'
- 'version as well which can'
- 'many other alternatives'
- ' Some other capable options are'
- 'Mac OS X/Linux :'
- 'It is shipped'
- 'requires some proficiency and comfort level with working with lower level tools'
- 'tool either from the browser or one that installs in your operating system.'
- ' follow the following steps'
- periods/colons after list items
- the: 'Visual C++ ' (x2+...)
- 'Next install'
- '- For 32-bit systems: Win32 OpenSSL v1.0.1j Light - For 64-bit systems: Win64 OpenSSL v1.0.1j Light'
- 'navigate to Windows sub-section'
- 'on the link cacert.pem and save'
- 'you placed curl.exe'
- 'Finally open your command prompt'
- 'curl.exe and run'
- 'run the command:'
- 'Where applicable, the curl command for making a request will be displayed throughout the book to help curl users.'

___

- ' launch your browser and enter the address https://www.reddit.com and this is a snapshot of'
- ' process the response that is sent back and display'
- 'text and presentation.'
- 'we don't get to see the raw response the server sent back'
- 'For that, we can use'
- 'tool and just like the browser did when we entered a URL in the address bar, we can'
- 'doesn't process the response and lets us see the raw response data,'
- ' is from the display in your browser'
- 'What you see here is, in fact, what your browser also receives, except it parses and processes that huge blob of data into a user-friendly format.'
- 'need to learn to read'
- ' raw data and do some debugging and see'
- 'and it's usually called'
- 'Using the Inspector' section is outdated
- ' Chrome Menu'
- ' Select Tools then Developer Tools.'
- ' the address https://www.reddit.com into your browser.'
- 'r still open click'
- 'the main page, www.reddit.com entry:'
- 'the specific request headers, cookies as well as the raw response data:'
- ' a ton'
- ' sent back, who initiated the requests'
- 'he resource we requested, the initial www.reddit.com entry, returned'
- 'And in that HTML body'
- 'other resources like images, css stylesheets, javascript files and more'
- ' Your browser, being smart and helpful, understands that in order to produce a visually appealing presentation, it has to go and grab all these referenced resources.'
- ' These other requests are to make sure the page displays properly on your screen, among other things.'
- 'Overall, you see that the browser's inspector gives you a good feel for these referenced resources.'
- 'A curl request will demonstrate this:'
- curl inconsistent backticks
- 'where reddit is the site'
- ' -A option'
- inconsistent single/double quotes for curl commands
- 'What you should see is just one request and the response containing the HTML, but no additional requests being automatically issued, like you see in a browser.'
- ' the information shown in these columns mean.'
- 'Important thing to'
- Status/Method columns are sometimes bold and sometimes italic
- ' a response, even if the response is an error -- that's still a response.'
- 'not 100% technically true'
- 'GET requests appear in a link or the address bar'
- 'address like https://www.reddit.com into'
- 'on the right panel.'
- 'command on their terminal:'
- 'https://itunes.apple.com/ with query strings'
- 'with parameter term=Michael%20Jackson where'
- 'and most links are GETs.'
- 'server, or send'
- 'to https://echo.epa.gov and the response'
- 'Typically from within'
- 'send much larger and sensitive data'
- 'URL; that isn't what we want'
- 'POST requests also help sidestep the query string size limitation that you have with GET requests'
- incosistent use of "you'll" vs. "we'll", etc.
- ' the Form URL-Encoded tab'
- 'Notice that in the screenshot and curl command we're'
- 'It has the same effect as'
- 'to the server since'
- 'answer to that is the HTTP body'
- ' data that is being transmitted in an HTTP message and is optional'
- 'audio and so on.'
- ' think of the body as the letter enclosed in an envelope, to be posted.'
- 'the HTTP tool or curl is'
- 'the field Location:'
- 'Location and its associated data is part of'
- 'about this yet as we'll'
- 'then issued ... then displayed'
-  'name-value' vs. 'name/value' -- inconsistent (x2+...)
- 'By using the Inspector, we can see these Headers.'
- 'both the request as well as the response headers:'
- 'headers under Request Headers'
- 'about the client and the resource to be fetched'
- backticks in Request Headers table
- 'request headers, but just know that it's part'
- 'GET/POST'
- 'most important components to understand about an HTTP request are:'
- add info about the Host header being required in HTTP 1.1
- inconsistent backticks for 'status code', 'status text', headers (ex: 'Location')
- 'request signifying'
- inconsistent backticks/italics/bold for status code number (ex: 302)
- backticks in tables
- ' is 200 which'
- ' server has encounter'
- 'status codes and their associated meaning'
- incosistent capitalization of 'browser' and inconsistent use of 'browser' vs. 'web browser'
- 'the account profile at'
- 'Github'
- 'resource can be anything including'
- 'images etc.'
- 'Because the resource we want does not exist, the browser shows us nice formatted text while the HTTP tool shows us the raw response with the status code.'
- ' (eg, your'

___

- 'techniques being employed'
- 'stays the same; you seem'
- 'common now that'
- 'cart can stay as you keep adding'
- 'It's obvious the stateless'
- ' augmented'
- 'the client (i.e., the browser),'
- 'forth the session identifier.'
- incosistent use of backticks/bold for 'session id'
- 'the previous or the next'
- 'Second, if this request does, in fact, contain a session id,'
- 'some rules with regards to how to handle'
- inconsistent use of "log/logged in to" vs "log/logged into"
- 'expensive HTML that your browser'
- 'likes and comments ... "like" link ... like count' (x2+...)
- 'out of scope of this book'
- 'browser cookie'
- ' Cookies or HTTP cookies, are'
- 'browser and contain the session information.'
- ' client side ... server-side'
- 'session data on each request to'
- ' are initiated with the help'
- 'We'll make a request to the address to https://www.yahoo.com'
- 'Note that if you're following along, you may have to use a different website if you already have an existing cookie from Yahoo.'
- ' navigate to that address'
- 'which implies it's'
- 'make a request and uniquely identifies'
- ' or more precisely, it identifies your client, which is your browser.'
- ' information would still be persisted.'
- 'Let's now revisit'
- ' status even though we'
- 'request after request.'
- ' each request is unrelated to each other and are not aware of each other'
- ' other - how'
- ' app "remember" we're'
- inconsistent use of backticks/capitalization for DevTools tabs (ex: 'Application') (x2+...)
- 'www.reddit.com where'
- ' value column:'
- 'That session id is saved into a cookie'
- 'now being sent ... now uniquely identify'
- 'on that id, and in that associated session data is where'
- 'while other times, it'
- 'key/value store'
- 'Where the session data is actually is'
- 'client, and it is used as'
- 'That's how web applications work around the statelessness of HTTP.'
- 'It is important to be aware of the fact that'
- 'a relatively short time'
- 'Last, we'll briefly mention'
- inconsistent use of backticks/capitalization of AJAX
- 'issue requests and process responses without'
- 'by performing some search on'
- 'google'
- 'the browser's inspector network tab ... Network tab'
- 'No doubt you've'
- 'performed searches many times and notice the'
- 'The Network tab however gives us'
- 'letter you type is issuing'
- 'key-press.'
- inconsistent wrapping of 'callback' in backticks
- 'logic you pass on to some function'
- 'to be executed'
- 'event has happened.'
- 'cookies and the session id in action'

___

- maybe use second person instead of first: ' someone steals my browser's session id, does that mean they can log in as me? ' (x2+...)
- ' what if ... does'
- 'what if I'm accessing a random website, can they'
- 'Reddit or Facebook cookie'
- ' issues; just common ones'
- 'all information in both requests and response'
- 'thereby automatically being logged in'
- 'With HTTPS every'
- 'request/response is'
- ' This means if a'
- ' called TLS for encryption'
- inconsistent use of backticks for 'SSL' and 'TLS'
- 'SSLor Secure Sockets Layer until'
- ' until TLS was developed'
- 'documents/resources'
- 'Documents in the same origin'
- ' hostname and port'
- ' share the same origin, have the same protocol, hostname and port number'
- '(the default port 80)'
- 'means documents'
- 'of files, and not linking'
- ' so Cross-origin resource sharing or CORS'
- 'which allow servers'
- ' hijacking (see next section) attacks'
- ' counter-measures'
- 'a session id serves as that unique token'
- 'client side now'
- 'this data is added'
- ' gets a hold'
- 'even know ... without ever even knowing'
- 'this means a'
- 'will not be able to have access'
- 'Another useful solution is by'
- 'can get to the session id.'
- 'text area'
- ' In this case an alert'
- ' HTML and JavaScript and be very'
- ' both the server as well as future'
- ' every future visitor ... assume their identity'
- ' `<script>` tags'
- ' or disallowing'
- ' input altogether in favor'
- 'If you do need'
- ' the term "escaping" above.'
- ' it; this'
- '`World!<\p>`'
- 'the browser uses detect when'
- '&lt;\p&gt;'
- ' then that HTML will be displayed as plain text instead.'
- ' is, and it's mostly'

___

- ' the internet and therefore a good'
- ' and what it means to be "stateless" are vital'
- ' threats like XSS, session hijacking and the countermeasures you need'
- 'learning HTTP'
- 'Re-reading, reviewing, exploring is normal'
- 'in your quest for greater understanding.'
- ' this book is ...  covered in this book'

___

___

lesson6 assignment:
- 'request response cycle'

//================================================================================//
//==============================================================================//*/
